### ISSUE TITLE
Parse MediaRSS feeds in RSS 2.0

### ISSUE THREAD

**Issue by evilpie** [feed-rs/feed-rs#101]
Youtube seems to use MediaRSS in an Atom feed and that is also what is supported by feed-rs, but looking at https://www.rssboard.org/media-rss, it says (my emphasis)
> This is version 1.5.1 of the Media RSS specification, a namespace for **RSS 2.0** published on Dec. 11, 2009

And indeed there are feeds like https://s.ch9.ms/Shows/Azure-Friday/feed/mp4high that have MediaRSS in RSS 2.0. It also has itunes tags, so finding some good way of merging those might be a bit tricky.

A workable approach might be to always prefer MediaRSS over itunes.

**Comment by markpritchard** [comment]
Thanks for finding that example feed @evilpie , I had a TODO in feed-rs to find one of these and pull it apart. 
I think MediaRSS over iTunes is a good plan - and coming up with some way of merging them into a sensible output while not losing too much information would be good too.

**Comment by evilpie** [comment]
Another example: https://podcasts.files.bbci.co.uk/b006qykl.rss

I am maintaining a collection of interesting feeds at https://github.com/nt1m/livemarks/wiki/Feed-URLs.

**Comment by evilpie** [comment]
https://www.omnycontent.com/d/playlist/5ac1e950-45c7-4eb7-87c0-aa0f018441b8/bb17ca27-51f4-4349-bc1e-abc00102c975/4c18e072-24d2-4d60-9a42-abc00102c97e/podcast.rss requires handling of itunes/enclosure and media:content.
