### ISSUE TITLE
RSS 1.0 no consistent GUID

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#11]
The RSS 1.0 parser uses the auto generated GUID from `Entry::default()`. This means parsing a feed a second time for new articles results in duplicate articles.
One could use the url to check for duplicates. But imo it would be nicer if `feed_rs` generated a consistent id for each item. Probably based on the url of the article.

**Comment by markpritchard** [comment]
I was wondering whether it would be a downstream user of feed-rs that would handle this logic, but since the spec doesn't define a unique ID at all in RSS 1.0 its reasonable to do something sensible in feed-rs. I'll push up a fix.

**Comment by jangernert** [comment]
Having the users of `feed_rs` handle the problem would also be acceptable. But in that case the ID should be `None`. Having a random string is quite misleading.
Anyway thank you for the fix =)
