### ISSUE TITLE
[Bad Feed] No ID & no Links

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#112]
Got a bug report for a particularly bad feed: https://gitlab.com/news-flash/news_flash_gtk/-/issues/213

https://feeds.feedburner.com/ingreso_dival

The issue is that the items don't have an ID or a Link. So random ids will be generated that break updating the feed.

A solution would be to combine the feed-URL with the title and has that to generate an ID. If you think that is an acceptable approach or have a better idea I can create a PR.

btw: is there ever a use-case for having randomly generated IDs? It caused more headaches for me than it solved problems. But that's just my experience.

**Comment by markpritchard** [comment]
Hey @jangernert , 

This is a really old format of RSS (0.91) and ID isn't actually a required element. I think your patch is good, but I'll add a test case for this so it doesn't break in the future. Interestingly, `link` is required ... but of course its the internet so who follows specs? :) 

https://www.rssboard.org/rss-0-9-1-netscape

For my use case I don't see repeated items in the old feeds but need an ID for the DB its stored in.

**Comment by markpritchard** [comment]
Fixed in #118
