### ISSUE TITLE
xml:base for content

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#114]
This is a follow up to #104 since this case was not covered by #107 

As mentioned in the previous issue: some feeds have relative URLs as part of their HTML content. A good example is https://insanity.industries/index.xml with

```
<item xml:base="https://insanity.industries/post/pareto-optimal-compression/">
...
<content:encoded><![CDATA[
    ...
    <figure>
        <a href="example.svg">
		    <img src="example.svg"
    	         alt="Compression results for different hypothetical compression algorithms, including the Pareto frontier indicated in blue."/>
        </a><figcaption><p>Compression results for different hypothetical compression algorithms, including the Pareto frontier indicated in blue.</p>
            </figcaption>
    </figure>
    ...
    ]]></content:encoded>
    ...
</item>
```

@markpritchard responded
> I'm comfortable switching all the URLs in the RSS/Atom content to absolute by applying xml:base but I wouldn't want to add an HTML parser to feed-rs by default. Might be worth playing around with as a feature (I've never done that in Rust ... might be interesting to learn).

**Comment by markpritchard** [comment]
This was picked up in #107 I believe (`xml:base` is used to set the `src` field of `Content`)

Feel free to re-open if I've misunderstood or missed something.
