### ISSUE TITLE
Parsing inaccuracies for "A List Apart" feed

### ISSUE THREAD

**Issue by roman-holovin** [feed-rs/feed-rs#120]
Feed URL: https://alistapart.com/main/feed

XML is dirty, full of redundant '\t' and '\n', I think trimming fields of the white-space before processing should resolve most issues, but I'm not sure on that.

**Comment by markpritchard** [comment]
Hi @roman-holovin 

`feed-rs` used to clean up whitespace, but it caused issues with the visual presentation in encoded content (ref #29) 

Best if users of the crate apply their own cleanup since they control what makes sense in their domain.
