### ISSUE TITLE
feed-rs is not able to parse out summary from RockPaperShotgun feed

### ISSUE THREAD

**Issue by roman-holovin** [feed-rs/feed-rs#121]
Feed URL: http://feeds.feedburner.com/RockPaperShotgun

This one I'm not sure why is not working. There is a `description` tag inside XML, it contains escaped HTML, but `feed-rs` returns `None` for it.

**Comment by markpritchard** [comment]
Thanks for the bug report! 

Do you have some example XML that fails to parse? The referenced regression test passes.
