### ISSUE TITLE
Fails to parse logo for one some feeds

### ISSUE THREAD

**Issue by fenuks** [feed-rs/feed-rs#125]
When parsing https://www.spreaker.com/show/4273892/episodes/feed `channel.logo` field is always `None`, even though feed has an image tag:

```xml
        <image>
            <url>https://d3wo5wojvuv7l.cloudfront.net/t_rss_itunes_square_1400/images.spreaker.com/original/0dcd53afca70854beb456079fa25d3f1.jpg</url>
            <title>Lwowska Fala | Radio Katowice</title>
            <link>https://www.spreaker.com/show/lwowska-fala-radio-katowice</link>
        </image>
```

Other feeds that have same structure of `<image>` have `logo` correctly parsed.

I'm using `feed-rs` version `0.6.1`.

**Comment by markpritchard** [comment]
Thanks for the bug reort @fenuks - its a problem with the `googleplay` namespace. Its unrecognised by `feed-rs`, and folded into standard processing where it overrides the `image` handler.

Little tricky to fix, but I'll pull together a patch and update the tests.

**Comment by fenuks** [comment]
Huh, that's an interesting issue, I would say. There is `<itunes:image>` tag as well in that feed file.

**Comment by markpritchard** [comment]
Yes, `feed-rs` supports the `itunes` namespace, mapping content into the domain model. 
Ideally it only processes elements and namespaces with explicit support to avoid this kind of problem in the future (i.e. this fix)
