### ISSUE TITLE
Treat invalid timestamps as current time

### ISSUE THREAD

**Issue by markpritchard** [feed-rs/feed-rs#14]
Appears other feed readers simply default to the current time when the timestamp is not able to be parsed.

**Comment by serpilliere** [comment]
Maybe it could a interesting to use an `Option` on the date: So the end user can decide *himself* what to to in case of bad/not present date in the feed.
For example: If you default the date in case of bad parsing or absent date, I will have no way to know if the given date comes from the feed or is a default one, meaning the feed has just been modified...

**Comment by markpritchard** [comment]
That is a good point ... the parser is able to fix lots of common mistakes, and you could always open an issue if you find a feed with a date/time we might be able to fix easily. I'll push a fix.

**Comment by serpilliere** [comment]
Thank you for the fix @markpritchard !
