### ISSUE TITLE
Publish the latest version to crates.io

### ISSUE THREAD

**Issue by ndelvalle** [feed-rs/feed-rs#146]
The version published on crates.io does not reflect the latest changes on this repo. I was trying to fix and issue with RSS 2 `guid` attribute that was already solved on master.

Can we publish a new version please.
Thanks in advance ❤️

**Comment by markpritchard** [comment]
Hey @ndelvalle , sure thing - I can tidy up a few other PRs and issue a new version.

**Comment by ndelvalle** [comment]
Thanks for the release!
