### ISSUE TITLE
Cant serialize Feed parsed from string

### ISSUE THREAD

**Issue by zhanglun** [feed-rs/feed-rs#164]
I am trying to return feed parsed from string as JSON format with serde_json::to_string(), but i get this error.

```
error[E0277]: the trait bound `Feed: Serialize` is not satisfied
    --> src\cmd.rs:97:46
     |
97   |       println!("{:?}", serde_json::to_string(&res))
     |                        --------------------- ^^^^ the trait `Serialize` is not implemented for `Feed`
     |                        |
     |                        required by a bound introduced by this call
     |
     = help: the following other types implement trait `Serialize`:
```

There is no any feature like "serde" i can find in [document](https://crates.io/crates/feed-rs), How can i solve this problem？

**Comment by zperk13** [comment]
Started implementing it for a pull request, but it turns out chrono::DateTime does not implement serde::Serialize but instead uses rkyv, so it's no so straightfoward.

@zhanglun For your problem, I would recommend creating a struct that is similar to Feed, but just with the fields you want, then derive Serialize/Deserialize on that. Here's some code that might help you get an idea of a way to fix your problem.

```rust
use feed_rs::model::Feed;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
struct FilteredFeed {
    id: String,
    title: Option<String>,
    description: Option<String>,
    links: Vec<String>,
}

impl From<Feed> for FilteredFeed {
    fn from(f: Feed) -> Self {
        Self {
            id: f.id,
            title: f.title.map(|text| text.content),
            description: f.description.map(|text| text.content),
            links: f.links.into_iter().map(|link| link.href).collect(),
        }
    }
}
```

**Comment by zhanglun** [comment]
> Started implementing it for a pull request, but it turns out chrono::DateTime does not implement serde::Serialize but instead uses rkyv, so it's no so straightfoward.
> 
> @zhanglun For your problem, I would recommend creating a struct that is similar to Feed, but just with the fields you want, then derive Serialize/Deserialize on that. Here's some code that might help you get an idea of a way to fix your problem.
> 
> ```rust
> use feed_rs::model::Feed;
> use serde::{Deserialize, Serialize};
> 
> #[derive(Debug, Clone, Serialize, Deserialize)]
> struct FilteredFeed {
>     id: String,
>     title: Option<String>,
>     description: Option<String>,
>     links: Vec<String>,
> }
> 
> impl From<Feed> for FilteredFeed {
>     fn from(f: Feed) -> Self {
>         Self {
>             id: f.id,
>             title: f.title.map(|text| text.content),
>             description: f.description.map(|text| text.content),
>             links: f.links.into_iter().map(|link| link.href).collect(),
>         }
>     }
> }
> ```

Your reply inspired me, thank you so much

**Comment by iohzrd** [comment]
Sorry for posting on a closed thread, but if anyone wants a complete (or at least very close to complete) implementation of this, feel free to use mine...
https://github.com/iohzrd/identia/blob/a2ac66f4fff340ec5383cadf8341d45ffd28a876/src-tauri/src/webfeed.rs
