### ISSUE TITLE
Support for <description> tag

### ISSUE THREAD

**Issue by Qwertie-** [feed-rs/feed-rs#170]
It looks like currently there is no way to access the data inside an item description https://www.rssboard.org/rss-draft-1#element-channel-item-description

**Comment by markpritchard** [comment]
Hi @Qwertie- , you'll find `channel.item.description` element mapped to the `Entry#summary` field in the model

https://github.com/feed-rs/feed-rs/blob/master/feed-rs/src/parser/rss2/mod.rs#L223

Hope this helps!

**Comment by Qwertie-** [comment]
Ah you are right. Perhaps it would be useful to add something to the generated docs that mention the summary comes from the description tag?

**Comment by markpritchard** [comment]
Yep, good call. Will expand the doco.
