### ISSUE TITLE
Idea: Add a hashmap to feed

### ISSUE THREAD

**Issue by fundon** [feed-rs/feed-rs#177]
Many feed structures don't follow the standard, so you can add a hashmap to hold this non-standard data and let the user handle it themselves

Likes: `updated` and `published`.

**Comment by markpritchard** [comment]
Hi @fundon , thanks for the idea. The challenge with a hashmap would be modelling the keys and values ... we'd need to handle namespaces, parent paths, node names + attributes, content etc. i.e. all the information emitted by the XML parser.

However, another alternative would be a callback that could be invoked when encountering unknown namespaces/nodes. You could then extract whatever information is useful and store it in a convenient data structure outside feed-rs more aligned with your use case.

That being said, it is a decent sized change to both the internals + external API so unless there is a lot of interest I don't see much utility in adding this.

Have you thought about parsing the content yourself separately and extracting the bits you need?

Alternatively, if you consistently see fields that feed-rs misses, then you are welcome to open requests for those - we've added support for new namespaces and alternate/incorrect element names previously.

**Comment by markpritchard** [comment]
Date/time formats not following the spec is a very common problem. There are a number of workarounds already such as trying the different ISO standards even across the "wrong" RSS/Atom formats. Perhaps you can share some of the common broken formats you run into and we can extend the parsing code in `feed-rs` to handle it?

**Comment by fundon** [comment]
I'm currently working on the HTML parsing and rendering issues, and I'll sort them out later.

**Comment by markpritchard** [comment]
OK, thanks for the update @fundon . I'll close this issue. 
Feel free to raise any issues with date/time formats in the future and we can look at addressing them.
