### ISSUE TITLE
Consistent GUID for feeds

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#18]
Similar to #11 feeds have randomly generated IDs for RSS 1.0 and 2.0. Atom parses an ID if it's there but could also end up with a random ID (not sure if that happens in the real world).
Would be cool to have a similar solution for this than #13 .

**Comment by markpritchard** [comment]
I reworked the assignment of IDs in #19  - feeds and entries missing IDs will now be assigned IDs from the first link, or a UUID if no links are available.
