### ISSUE TITLE
Handling badly malformed dates

### ISSUE THREAD

**Issue by amoskvin** [feed-rs/feed-rs#182]
feed-rs tries all sorts of fixes to make dates parseable, but it seems like an exercise in futility since websites find countless creative ways to mess them up.

For example, I'd like to parse https://www.nbcnewyork.com/?rss=y, which has publication dates in this format:
```xml
<pubDate>Fri, Feb 24 2023 08:18:00 PM</pubDate>
```
Even if a fix for AM/PM was added, it would still be wrong since there's no way to tell it's actually in New York time.

Likewise, the fix for #165 doesn't actually work when the months don't match English abbreviations. For example, in https://www.ilmessaggero.it/rss/donna.xml you can find:
```xml
<pubDate>sab, 07 gen 2023 21:44:32 +0100</pubDate>
<pubDate>gio, 29 dic 2022 11:13:20 +0100</pubDate>
<pubDate>mar, 18 ott 2022 13:28:06 +0200</pubDate>
```
Would it make sense to have the model expose the original raw string? Or add a way to plug in a custom date parser?

**Comment by markpritchard** [comment]
Hi @amoskvin , I'd prefer not to expose the raw string as that breaks the idea of the feed-rs data model.

However, I think adding a custom date parser is a good idea - you could supply it on the `parse` call (I've been meaning to refactor this to follow a builder pattern).

**Comment by lukehsiao** [comment]
I have another one to add to this list. I'd like to parse

https://morepablo.com/feeds/all.atom.xml

Which has dates in the format

```
<published>2023-07-19T23:37:38</published>
<updated>2023-07-19T23:37:38</updated>
```

This is missing timezone information, but I'd by happy to parse this myself and just call it a naive date or assume it is on my local timezone (even if it's not).

**Comment by markpritchard** [comment]
Hopefully its fairly self-explanatory to use, but you can also find a test here: https://github.com/feed-rs/feed-rs/pull/201/files#diff-05b0e9bf4f69b6d5949223a3f18427058b896779ada65f2d7c3f5e5aa0051a9dR751

**Comment by markpritchard** [comment]
Feel free to raise another issue if this doesn't work for you... you can also call `util::parse_timestamp_lenient` from your implementation to handle more typical data.
