### ISSUE TITLE
RSS 2.0 without `guid` field

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#19]
Just stumbled across the [`trailers.apple.com`](https://trailers.apple.com/trailers/home/rss/newtrailers.rss) RSS 2.0 feed which doesn't provide a `guid` for articles. So the same issue as #11 arises.

Sorry to open up so many issues. But I'm using this crate quite a lot :)

**Comment by markpritchard** [comment]
Sorry, I forgot to watch the repo and didn't get notified of your issues! I'll take a look at them and get back to you.

Great to hear you are using the crate :)
