### ISSUE TITLE
JSONFeed v1.1 support?

### ISSUE THREAD

**Issue by hongquan** [feed-rs/feed-rs#190]
Hi

JSONFeed [v1.1](https://www.jsonfeed.org/2020/08/07/json-feed-version.html) has been out for 3 years. It would be nice if feed-rs supports it.

**Comment by markpritchard** [comment]
@hongquan thanks for the link to the spec

Looks like the only gaps are:
* Added authors field to allow more than 1 author per feed or item. Deprecated author.
* Added language field.

Have you found any other issues?

**Comment by hongquan** [comment]
No. I think only those two is enough.
