### ISSUE TITLE
could not parse atom feed https://www.scattered-thoughts.net/atom.xml

### ISSUE THREAD

**Issue by gleroi** [feed-rs/feed-rs#205]
This feed typed its content as "text/html" and only put `<a href="<blog_link>">some text</a>` in it :
```
 <entry xml:lang="en">
    <title>Examining scampy</title>
    <published>2010-05-19T00:00:00+00:00</published>
    <updated>2010-05-19T00:00:00+00:00</updated>
    <link href="https://www.scattered-thoughts.net/writing/examining-scampy/" type="text/html" rel="alternate"/>
    <id>https://www.scattered-thoughts.net/writing/examining-scampy/</id>
    <content type="text/html"><a href="https://www.scattered-thoughts.net/writing/examining-scampy/">Examining scampy</a></content>
  </entry>
```

The atom parser fails with the following error:
`unable to parse feed: missing content element content.inline`

I tracked the error to this line of code: https://github.com/feed-rs/feed-rs/blob/9bbb5afa7827ad5574a0bdb8ca8513c6def1b50a/feed-rs/src/parser/atom/mod.rs#L125-L138

It should be `children_as_string` i think.

**Comment by markpritchard** [comment]
Thanks for the bug report @gleroi 

The problem is that the feed incorrectly specifies a mime type for the content->type attribute. But its likely not the only feed to make that mistake, so feed-rs will now correctly parse this.
