### ISSUE TITLE
Itunes subcategories are not parsed

### ISSUE THREAD

**Issue by sophiawisdom** [feed-rs/feed-rs#215]
For example in https://anchor.fm/s/8d364524/podcast/rss ([saved here](https://gist.github.com/sophiawisdom/fc07ed886cf8687c298628a4423bbf58)) there is both a category and a subcategory:

```
		<itunes:category text="Kids &amp; Family">
			<itunes:category text="Parenting"/>
		</itunes:category>
```

However, only the enclosing category ("Kids & Family") shows up as a Category. Here's a [debug print of the parsed feed](https://gist.github.com/sophiawisdom/5e7ad07b5f02f83f17535d9383ed199c).

**Comment by markpritchard** [comment]
Hi @sophiawisdom , the itunes namespace spec (closest I could find is https://help.apple.com/itc/podcasts_connect/#/itcb54353390) does document subcatgories, but none of the other feed formats describe anything other than a list as far as I can see.

We can flatten subcategories into a list, combining them with a separator such as `/` I guess, but it would be a decision feed-rs makes independent of any specification.
