### ISSUE TITLE
Media RSS player tag unsupported

### ISSUE THREAD

**Issue by sziegler** [feed-rs/feed-rs#242]
Vimeo RSS feeds use media:player instead of providing a URL.  According to the spec this is legal. 

From [the spec](https://www.rssboard.org/media-rss#media-content):
> url should specify the direct URL to the media object. If not included, a <media:player> element must be specified.

But it seems the code is ignoring entries without the url attribute

Here is an example from https://vimeo.com/user110157601/videos/rss 

```
    <item>
      <title>Harvest 2024 Begins!!</title>
      <pubDate>Thu, 22 Aug 2024 10:33:17 -0400</pubDate>
      <link>https://vimeo.com/1001620795</link>
      <description>The air is brisk the sky is bright and our first pick of the 2024 harvest is underway with a small block of our Olivet Ranch Swan Clone Pinot Noir!</description>
      <guid isPermaLink="false">tag:vimeo,2024-08-22:clip1001620795</guid>
      <media:content medium="video" duration="139">
        <media:player url="https://player.vimeo.com/video/1001620795?h=cdeac610af"/>
        <media:credit role="author" scheme="urn:ebu">Failla Wines</media:credit>
        <media:thumbnail height="540" width="960" url="https://i.vimeocdn.com/video/1917857543-1aa3068f3196b99af9cadf40d4602c9691cddf083465b2d085d92c0e962d7b5f-d_960"/>
        <media:title>Harvest 2024 Begins!!</media:title>
      </media:content>
    </item>
```

It would be great to be able to retrieve the player url

**Comment by markpritchard** [comment]
Thanks for the great bug report @sziegler , especially the pointer to the spec. Made it easy to understand and fix.
