### ISSUE TITLE
Panics on invalid XML

### ISSUE THREAD

**Issue by gperinazzo** [feed-rs/feed-rs#26]
The library currently panics on the following input:
```
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0"
	
>
<channel>
<title>Reuters: Most Read Articles</title>
<link>https://www.reuters.com</link>
<description>Reuters.com is your source for breaking news, business, financial and investing news, including personal finance and stocks.  Reuters is the leading global provider of news, financial information and technology solutions to the world's media, financial institutions, businesses and individuals.</description>
<image>
	<title>Reuters News</title>
	<width>120</width>
	<height>35</height>
	<link>https://www.reuters.com</link>
	<url>https://www.reuters.com/resources_v2/images/reuters125.png</url>
</image>
<language>en-us</language>
<lastBuildDate>Sat, 21 Mar 2020 06:29:51 -0400</lastBuildDate>
<copyright>All rights reserved. Users may download and print extracts of content from this website for their own personal and non-commercial use only. Republication or redistribution of Reuters content, including by framing or similar means, is expressly prohibited without the prior written consent of Reuters. Reuters and the Reuters sphere logo are registered trademarks or trademarks of the Reuters group of companies around the world. &#169; Reuters 2020</copyright>
<!--Property passed to loop is null--><!-- Exception rendering module on server  -->
 ```
This is being served by the following url (at the time of writing): http://feeds.reuters.com/reuters/MostRead

The panic is due to an unwrap on `src/util/element_source.rs:250:9`, and can be verified with the testurls example:
```
$ echo "http://feeds.reuters.com/reuters/MostRead" | cargo run --bin testurls
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/testurls`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { pos: 22:1, kind: Syntax("Unexpected end of stream: still inside the root element") }', /home/guilherme/Projects/feed-rs/feed-rs/src/util/element_source.rs:250:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
http://feeds.reuters.com/reuters/MostRead
```
Other inputs that will also panic:
- [From https://olhardigital.com.br/rss/ultimas_noticias.php](https://github.com/feed-rs/feed-rs/files/4363814/case1.txt): Missing channel opening tag, but has the channel closing tag.
- [From http://bankimplode.com/rss.xml](https://github.com/feed-rs/feed-rs/files/4363893/case2.txt): unescaped ampersand in an item title

**Comment by markpritchard** [comment]
Thanks for the bug report @gperinazzo , will take a look and get it fixed!

**Comment by gperinazzo** [comment]
I'm looking over the code to see how can this be fixed. The problem is that `ElementIter` is an iterator over `Element`, but finding an element may fail.

Changing it to iterate over a `Result<Element>` would allow the error to be properly handled by the caller, but it makes the caller a lot more complex to deal with this failure. Changing this would require changing every call site that uses `.children`.

Changing it to return None if an error occurred works without modifying any call sites, but has the side effect of hiding any errors that may occur. So some invalid feeds will seem to successfully but may return incomplete data (up to the point where the error happened). 

From my examples, both `reuters` and `bankimplode` return successfully when transforming errors into None, while the `olhardigital` feed still fails due to missing a root element. `bankimplode` returns entries up to the entry with an unescaped ampersand on the title, and that entry is incomplete.

I would like to help fixing this, do you have any suggestions on how it could be fixed?

**Comment by markpritchard** [comment]
I think an invalid feed should fail to parse (e.g. missing content like the Reuters feed) since you don't know what you are going to get. 

But it shouldn't panic i.e. feed-rs should return you an `Err` with the appropriate information. 

These are great examples btw, I'd only found valid feeds in my research for "real" examples.

Thanks for the offer of help with a fix :) If you are interested in submitting a patch that allows the iterator to fail, that would be great ... and return an `Err` that can be checked. I'll prep a patch myself too (I use `feed-rs` to learn Rust, so curious to see how I can solve it as well).

**Comment by gperinazzo** [comment]
I got the patch ready, just going to run it through a list of about 4000 RSS urls that I have to see if I can catch any more panics.

**Comment by gperinazzo** [comment]
My list didn't wield any panics, I'll open another issue with valid feeds that it failed to parse.
