### ISSUE TITLE
Overeager whitespace trimming

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#29]
I'm not sure if this is an issue with `xml-rs`, but lets go one level deeper at a time.
Apparently `feed-rs` trims the spaces before and after links for the `planet.gnome.org` [atom feed](https://planet.gnome.org/atom.xml). I tracked the issue down to [`element_source.rs:L30`](https://github.com/feed-rs/feed-rs/blob/master/feed-rs/src/util/element_source.rs#L30). Setting `trim_whitespace(false)` "fixes" the issue.

Do you think turning whitespace trimming off is a sensible solution for this bug? Should this be reported to `xml-rs`?

Original report with image illustrating the issue: https://gitlab.com/news-flash/news_flash_base/-/issues/9

**Comment by markpritchard** [comment]
Thanks for the great bug report @jangernert . I've got a fair bit on at the day job at the moment, but I'll take a look this evening.

As an aside, I turned this on to simplify consumption of the feed programmatically (so clients didn't all have to trim whitespace themselves), but perhaps this is overeager on element transition as you mention. Anyway, will dig into it this evening.

Thanks again!

**Comment by jangernert** [comment]
Would you accept a PR that just deactivates the white-space trimming for now? We can take further actions once issues because of it arise. But for now at least I don't see a disadvantage.

**Comment by markpritchard** [comment]
Sure, that is fine for now @jangernert . 

I'm planning on releasing 0.3 in a little while which will introduce parsing of other namespaces (eg. DublinCore) to handle elements such as `dc:date` in rss1 feeds. This is a decent size change, which people may not want to opt into, so it will come with a configuration concept. This could be used to address the white-space trimming too.

Could you add a test case to ensure the updated white-space trimming meets your needs? That way we have a regression test for the future too.

Thanks!
