### ISSUE TITLE
What is the real license of a project?

### ISSUE THREAD

**Issue by ignatenkobrain** [feed-rs/feed-rs#37]
Cargo.toml says it is `MIT or Apache-2.0` but LICENSE file contains only MIT text license…

Would appreciate new release after you decide which one is correct and make necessary corrections.

Thanks!

**Comment by markpritchard** [comment]
Hi @ignatenkobrain , I'm not across why the original author chose to dual license it but I'm happy with MIT as the more permissive license.

**Comment by ignatenkobrain** [comment]
Thanks for confirming!
