### ISSUE TITLE
Tests from archive crates.io fail

### ISSUE THREAD

**Issue by ignatenkobrain** [feed-rs/feed-rs#38]
Hello,

I'm packaging feed-rs as one of dependencies for Fedora and we run `cargo test` on all crates we package. However, it seems that testing files are not shipped (the `fixtures` folder). Is there reason not to?

If there is, can you probably also exclude `src/util/test.rs` so that cargo test won't run it?

Thanks for cooperation!

**Comment by markpritchard** [comment]
Hi @ignatenkobrain ,

Curious ... I didn't realise Fedora was shipping rust crates. Thanks for reaching out about the issue with `fixture`. Will include it in the release.

**Comment by ignatenkobrain** [comment]
Thanks! Here is some description why we actually do so: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/UE4FU27OAHXQ2EOV5OFSXGHELUWZYSJM/ :)

**Comment by markpritchard** [comment]
That is great, thanks for the info. I'm wondering how this tiny little project I picked up maintenance for ended up being packaged in Fedora :) Do you have the dependency chain to satisfy my curiousity? No trouble if its difficult - its really just interest.

**Comment by ignatenkobrain** [comment]
I think is coming directly from https://gitlab.com/news-flash/news_flash_base which is used from https://gitlab.com/news-flash/news_flash_gtk

**Comment by markpritchard** [comment]
Super, thank you!
