### ISSUE TITLE
More forgiving datetime parsing

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#43]
Original report: https://gitlab.com/news-flash/news_flash_base/-/issues/24

The issue:

The date format is a little off
```
2014-12-29T14:53:35+0200
```
instead of
```
2014-12-29T14:53:35+02:00
```

Imo `feed-rs` should try a few common formats until giving up to parse a date.

The atom feed is: https://feeds.feedburner.com/sallar

Maybe something like `RFC2822_FIXES` for rfc3339 would make sense here. Sadly my knowledge of regular expressions is somewhat limited.

**Comment by markpritchard** [comment]
Thanks for the patch @jangernert ! I switched to lenient parsing by default ... the idea was to start strict and just add sensible regex rewrites. Surprised it took this long for you to find an issue in RFC3339 dates :) 

Appreciate you taking the time to add the test case as well.

**Comment by jangernert** [comment]
And I'm surprised in how many ways people manage to implement these standards wrong. Almost harder to come up with these subtle deviations than to implement it according to spec.

**Comment by markpritchard** [comment]
Especiailly since pretty much every language has simple formatters to
generate strings from native date/time types! :)
