### ISSUE TITLE
Get feed type

### ISSUE THREAD

**Issue by ayrat555** [feed-rs/feed-rs#48]
Is it possible to determine the type of parsed feed (rss , atom , json) ?

**Comment by markpritchard** [comment]
Hi, at the moment feed-rs doesn't export this but its pretty easy to implement. I'll add it to the list and cut a new release soon. Thanks!

**Comment by ayrat555** [comment]
Thank you. I would be very helpful. Currently, I'm using feed-rs to parse json feeds for https://github.com/ayrat555/el_monitorro. I check if it's json feed by parsing a string with serde.
I will completely migrate to `feed-rs` when the type will be available

**Comment by markpritchard** [comment]
Fixed in #51
