### ISSUE TITLE
RSS `content:encoded` does not get parsed as an entry body

### ISSUE THREAD

**Issue by Bauke** [feed-rs/feed-rs#49]
Hi, (great library, I really appreciate the efforts in creating a unified feed parser!) after using `feed-rs` for a bit and wanting to swap over to it in a project, I noticed that the entry bodies of certain feeds weren't being included, they always ended up unwrapping to `None`. After looking a bit at the feed data, I think it's because the `content:encoded` element isn't being parsed into the model as a body.

I looked at the tests to see if it was covered (and thus if I was doing something wrong) and noticed that while there is a sample file that has `content:encoded` in it:

https://github.com/feed-rs/feed-rs/blob/949c3ea835aa215a068f42dca705a42c99638d83/feed-rs/fixture/rss_2.0_example_4.xml#L49-L55

The body for it isn't being tested:

https://github.com/feed-rs/feed-rs/blob/949c3ea835aa215a068f42dca705a42c99638d83/feed-rs/src/parser/rss2/tests.rs#L116-L126

**Comment by markpritchard** [comment]
Hey @Bauke , thanks for the feedback! 

The `content:encoded` element is an interesting case - its not in the actual spec, but a standardised namespace. There is #25 which handles these expected namespaces, and I'll implement that soon. Will also pick up #50 to implement the other recommendations.

I'm going to release it as 0.3.0 soon (hopefully next few weeks).
