### ISSUE TITLE
Create a separate field for feed_url

### ISSUE THREAD

**Issue by ayrat555** [feed-rs/feed-rs#57]
Can you please create a separate field in the feed model for feed url? 

Currently, the feed model has `links` field. It's not obvious in which position feed url is localed for json feed. Json feeds have `feed_url` and `homepage_url`

Another option is to get rid of `links` field and create `link` field which will contain feed url

**Comment by markpritchard** [comment]
Hey @ayrat555 , curious about the use-case behind this? Wouldn't you have the URL when retrieving the feed?

I could extend `feed-rs` to try and populate the canonical feed URL but its not guaranteed to be present in the content itself (optional in RSS, Atom and JSON Feed).

**Comment by ayrat555** [comment]
Hi. I'm sorry for a later reply.

I want to have a separate field for the feed url to use it instead of a user-provided URL which could point to another source that is redirected to the feed url. It's related to https://github.com/feed-rs/feed-rs/issues/53#issuecomment-640006828. 

Now I may potentially have duplicated feeds in the DB.

**Comment by jangernert** [comment]
Couldn't you just get the redirected URL when downloading the feed? The HTTP client should definitely provide a way to do this.

**Comment by markpritchard** [comment]
@ayrat555 I think @jangernert 's solution is the best one.

The links in the feed itself are to the HTML version of the associated site (RSS2, Atom). There isn't a link to the feed content itself i.e. a canonical URL for the feed.

**Comment by ayrat555** [comment]
Thanks for looking into the issue

**Comment by markpritchard** [comment]
No worries, thanks for raising it :) Its great to hear people are using the library, so always feel free to raise questions / suggestions!
