### ISSUE TITLE
Convert text to Utf-8

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#58]
I'm not sure if this is something that should be implemented in `feed-rs` itself or rather in `xml-rs`.
I think we all know rust strings are utf-8 and XML documents of feeds can be in a number of different encodings. The text encoding used is mentioned in the xml tag like this:

`<?xml version="1.0" encoding="ISO-8859-1" ?>`.

`xml-rs` [picks up](https://docs.rs/xml-rs/0.8.3/xml/reader/enum.XmlEvent.html#variant.StartDocument.field.encoding) that information, but doesn't do anything with it until now.
> XML document encoding.
>
>If XML declaration is not present or does not contain encoding attribute, defaults to "UTF-8". This field is currently used for no other purpose than informational.

So the question is: should the text be converted to uft-8 in `xml-rs` already or is `feed-rs` the right place to handle this? Even if it eventually should be part of `xml-rs`'s functionality, is a temporary solution in `feed-rs` a good idea?

Obligatory link to the related bug report in an application using `feed-rs`:
https://gitlab.com/news-flash/news_flash/-/issues/35

**Comment by markpritchard** [comment]
I think its worth digging into xml-rs a little.

I'd expect a parser that handles a raw byte stream to return valid UTF-8 Rust `String`s i.e. use BOM markers, encoding hints etc to determine the source encoding and build correct Unicode strings.

Seems like https://crates.io/crates/encoding is the go to crate for encoding. I'll look into a PR against xml-rs to implement it. If the maintainer of xml-rs is against the idea, we could update feed-rs to detect it and hopefully re-interpret the strings but that feels pretty hacky (get the raw bytes backing the incorrectly decoded String, convert it to unicode, convert it back to a String again).

**Comment by jangernert** [comment]
I see no easy way to do a better implementation in `xml-rs`. I hacked something together quickly: https://github.com/jangernert/xml-rs/commit/229e715d476a0fff9b7f7c08739fc5a34391d44a

I still take the stitched together string and feed it `as_bytes()` to `encoding`. Otherwise the encoding has to be propagated very deep and every single character has to be decoded separately. I'm not sure but I think this would be quite a bit slower and a mayor PITA.

But I don't have a very good overview of the `xml-rs` code base. Just had a short look. Maybe you or the `xml-rs` maintainers can come up with something better.

**Comment by markpritchard** [comment]
@jangernert I did a bit of research into this and its pretty simple to convert ISO-8859-1 to UTF8, so I'll prepare a patch for `xml-rs` that adds generic encoding support. I'll change the dependency on `feed-rs` to my fork of `xml-rs` and push another release shortly.

**Comment by markpritchard** [comment]
Hey @jangernert I had a good look at your PR for `xml-rs` and it seems fine to me ... not a hack at all. The XML spec at https://www.w3.org/TR/xml/#NT-EncodingDecl mentions the encoding applies to _content_ so I don't think it makes sense to convert character by character especially given multi-byte encodings etc. Perhaps submit it to the maintainer of `xml-rs` for inclusion?

**Comment by jangernert** [comment]
Okay, cleaned it up a bit and posted it: https://github.com/netvl/xml-rs/pull/196
Let's hope the maintainer reacts. There are already some older MR piling up and https://github.com/netvl/xml-rs/pull/174#issuecomment-602151332 is not encouraging.
