### ISSUE TITLE
GitHub releases atom feeds fail to parse

### ISSUE THREAD

**Issue by wezm** [feed-rs/feed-rs#6]
E.g. https://github.com/feed-rs/feed-rs/releases.atom

`ParseError(MissingContent("content.type"))`

**Comment by markpritchard** [comment]
Thanks for the bug report @wezm - its curious, I grabbed the feed and wrapped a test case around it. Worked fine.

Could I trouble you to provide some more details on how you generated the data and tested it?

**Comment by wezm** [comment]
I wrote a little tool that takes URLs and fetches each one with attohttpc then tries to parse it with feed-rs. All the GitHub ones that I subscribe to failed with that error. Running it again now though they seem fine. Perhaps it was an issue on GitHub's end.
