### ISSUE TITLE
Implement media spec support

### ISSUE THREAD

**Issue by kkszysiu** [feed-rs/feed-rs#68]
The library is great!

I think for me the only missing piece is support for media namespaces handling.
The spec is here: https://www.rssboard.org/media-rss

Sadly lots of RSS/Atom feeds is using it, including Youtube atom feeds: https://www.youtube.com/feeds/videos.xml?user=kkszysiu

I think having support for it would be great.
I will try to introduce a PR that adds at least basic implementation in the comming days.

**Comment by markpritchard** [comment]
@kkszysiu glad to hear you find the library useful :) 

Would be good to add media-rss - thanks for raising the ticket. Looks quite straightforward, most interesting part will be mapping it to the underlying model. A quick bit of Google research turns up articles like https://bjohas.de/wiki/Enclosures_in_yahoo_media,_rss,_and_atom which mentions Atom as well, so having a look at a few different feeds would be interesting to try and figure out a common data model would be great.

I'll have a bit of a poke around too.

**Comment by kkszysiu** [comment]
Yes, seems like both RSS and Atom might contain in.
The other interesting thing is that these seems to be directly places into item, they might be inside <media:content> or inside <media:group> contining multiple <media:content> branches, which is kind of hard to handle I think.

For example newscred, one of the feeds we are using, is doing something like this:
```xml
  <entry>
    <id>75ffea6b731bb4534f3138fd6b726791</id>
    <title>The Day Off: Tampa</title>
    <updated>2019-04-05T21:04:41+00:00</updated>
    <author>
      <name>Some author</name>
    </author>
    <content type="html"><![CDATA[Some text]]></content>
    <link href="http://www.example.com/the-day-off-tampa" rel="alternate"/>
    <published>2019-04-05T21:04:40+00:00</published>
    <media:content url="https://www.example.com/Zz1hNjRiMWFjMzdhYWIzNTEwNjk2YjIzYjc5NWQxNWFlMA==/.jpeg" medium="image" width="2048" height="1365" type="image/jpeg">
      <media:title type="plain"></media:title>
      <media:description type="plain"></media:description>
      <media:text type="plain"></media:text>
      <media:credit>Cool Magazine</media:credit>
    </media:content>
    <media:thumbnail url="https://www.example.com/Zz1hNjRiMWFjMzdhYWIzNTEwNjk2YjIzYjc5NWQxNWFlMA==?width=75&amp;height=75" width="2048" height="1365"/>
  </entry>
```

While YT is grouping these:
```xml
<entry>
	<id>yt:video:EV6uVekLnxo</id>
	<yt:videoId>EV6uVekLnxo</yt:videoId>
	<yt:channelId>UCAEgFGKjju9HWzUeIasBtJw</yt:channelId>
	<title>Flume Poznań 10.11.2016(8)</title>
	<link rel="alternate" href="https://www.youtube.com/watch?v=EV6uVekLnxo"/>
	<author>
		<name>Krzysztof Klinikowski</name>
		<uri>https://www.youtube.com/channel/UCAEgFGKjju9HWzUeIasBtJw</uri>
	</author>
	<published>2016-11-12T13:04:02+00:00</published>
	<updated>2018-02-22T05:04:56+00:00</updated>
	<media:group>
		<media:title>Flume Poznań 10.11.2016(8)</media:title>
		<media:content url="https://www.youtube.com/v/EV6uVekLnxo?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
		<media:thumbnail url="https://i2.ytimg.com/vi/EV6uVekLnxo/hqdefault.jpg" width="480" height="360"/>
		<media:description/>
		<media:community>
			<media:starRating count="0" average="0.00" min="1" max="5"/>
			<media:statistics views="146"/>
		</media:community>
	</media:group>
</entry>
```

So quite different approaches, but both seems valid according to spec...

**Comment by markpritchard** [comment]
Yes, the spec is quite flexible in what it allows - grouping of media:content elements (variations of the same content I presume vs. separate pieces of content). Also allows many optional elements across `channel` and `item`

I started preparing a PR to add this, but wanted to just float an idea ... 

One of the goals of `feed-rs` is to simplify using these feeds, and I noticed this in the spec:
> Duplicated elements appearing at deeper levels of the document tree have higher priority over other levels. For example, <media:content> level elements are favored over <item> level elements. The priority level is listed from strongest to weakest: <media:content>, <media:group>, <item>, <channel>.

Rather than extending the `Feed` and `Element` structures in the model and forcing users of feed-rs to track this state themselves and do the propagation / deduplication I was thinking of just handling this internally. So feed-rs might see `media:title` on an RSS `item` element and automatically set on the `media:content` item unless it is already present at that level.

This approach also lets feed-rs do sensible things like setting a title for an `item`/`Element` if not present in the feed from the `media:title` etc. i.e. we can make the output more "complete" by propagating content across the domain model automatically where permitted by the specs.

Sound reasonable?

**Comment by kkszysiu** [comment]
@markpritchard , this propagation would be only for `media:*` elements, right?
If yes, then yeah, I was thinking about doing the same thing and it makes total sense, plus it seems to be exactly what the specs are defining.

**Comment by Galaf** [comment]
Thank you for this library!

It is a real time-saver for the project I'm currently implementing.
Do you think this feature will be implemented anytime soon?

While I can go around it by poking some REST endpoints, I'd prefer to be able to save everything I need from the Atom feed directly in one iteration.

Thank you for your time!

**Comment by azmeuk** [comment]
[Related newsflash ticket](https://gitlab.com/news-flash/news_flash/-/issues/14)

**Comment by markpritchard** [comment]
Thanks @Galaf , glad you find the library useful.

I was working on this a little while ago but got distracted on some other things. Will dig out the branch and finish it off (especially with the linked ticket to newsflash ... thanks for the extra poke @azmeuk :) )
