### ISSUE TITLE
Utf-8 getting decoded 2nd time

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#69]
Okay, I'm not sure if this can even be fixed without slowing down the parsing quite a bit. So possibly the solution is to close this issue and put a warning somewhere "Don't do this".

I'll use `testurls` as an example since it also triggers the issue.

The `text()` method of reqwest already tries to find the encoding in the HTTP headers and decodes the text to `utf-8`. Now we have a utf-8 encoded xml string which contains something like `<?xml version="1.0" encoding="ISO-8859-1"?>`.

So `feed-rs` or rather `quick-xml` does what it is told and interprets the bytes as `ISO-8859-1` and tries to convert them to `utf-8`. Sadly that just scrambles the nicely decoded characters again.

A stripped down version of `testurls`

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let xml = reqwest::blocking::get("https://rss.golem.de/rss.php?feed=RSS1.0")?.text()?;

    match parser::parse(xml.as_bytes()) {
        Ok(_feed) => println!("ok"),
        Err(error) => println!("failed: {:?}\n{:?}\n-------------------------------------------------------------", error, xml),
    }

    Ok(())
}
```

results in:

```
Some(Text { content_type: "text/plain", src: None, content: "Cloud-Computing: Cloudical kÃ¼ndigt kompletten Cloud-Open-Source-Stack an" })
```

Using raw `bytes()` instead of decoded `text()` works as expected

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let xml = reqwest::blocking::get("https://rss.golem.de/rss.php?feed=RSS1.0")?.bytes()?;

    match parser::parse(xml.as_ref()) {
        Ok(_feed) => println!("ok"),
        Err(error) => println!("failed: {:?}\n{:?}\n-------------------------------------------------------------", error, xml),
    }

    Ok(())
}
```

```
Some(Text { content_type: "text/plain", src: None, content: "Cloud-Computing: Cloudical kündigt kompletten Cloud-Open-Source-Stack an" })
```

Btw: that also explains why you couldn't reproduce #10 with `testurls`. Everything is starting to make sense to me.
I'll switch to `bytes()` in my code and see what opinions others have regarding this issue.

**Comment by markpritchard** [comment]
Great find and analysis @jangernert ! Very similar to issues I've run into in the past (e.g. Java servlet containers + URL parsing libraries both decoding parameters etc).

My initial thought is similar to yours - retrieving feeds over HTTP/S is just one storage/transport mechanism (albeit the most popular by far). Other sources might be a local database or file system, or some other mechanism that is "dumb" and does not provide transparent decoding like reqwest does.

So my preference would be to clearly state we expect the content to be in its original, encoded form (i.e. raw bytes) and feed-rs handles the decoding:
* it keeps the decoding approach consistent across all sources of content
* its convenient for users of the library (just provide raw bytes)

If it proves problematic in the future, feed-rs could be extended to not decode as required. 

I might push a change that makes it clear in the documentation + update testurls to use `.bytes()` too as a basic reference implementation. Sound reasonable?

**Comment by jangernert** [comment]
Yes, I think a clear description in the docs of [`parse`](https://docs.rs/feed-rs/0.4.0/feed_rs/parser/fn.parse.html) and fixing `testurls` would be an acceptable solution.
