### ISSUE TITLE
feature request: support for Atom Entry Documents

### ISSUE THREAD

**Issue by hober** [feed-rs/feed-rs#70]
I have an aging website whose backing store is a whole pile of [Atom Entry Document](https://tools.ietf.org/html/rfc4287#section-2)s, and I'm contemplating replace the Python script that processes them with a Rust program. But it doesn't look like your library supports these kinds of documents: https://github.com/feed-rs/feed-rs/blob/master/feed-rs/src/parser/mod.rs#L180 doesn't look for `entry` root elements.

**Comment by markpritchard** [comment]
That is interesting, I based the Atom parser on http://www.atomenabled.org/developers/syndication/ and not RFC 4287. Seems easy enough to fix though, given its just an `atomEntry` without a parent feed.

feed-rs will need to return a basic, empty `Feed` as a parent to keep the API consistent.

**Comment by markpritchard** [comment]
Hi @hober , seemed fairly straightforward. Hope this works for you! :)
