### ISSUE TITLE
Implment Clone on feed_rs::model::Entry ?

### ISSUE THREAD

**Issue by eddyp** [feed-rs/feed-rs#73]
I'm trying to use feed_rs to make some aggregator-like tool with some filtering capabilities.

For this to work I came up with the idea of getting sources from different feeds, merge them into a single "stream" and to apply the filters I need, but I got stuck because I can't concatenate the feed_rs::model.entries (which is a Vec<Entry>) as the feed_rs::model::Entry does not implement the Clone trait.

Is this intentional? is there a good reason why this as is, or is it just an issue was never problematic?

**Comment by markpritchard** [comment]
Hi @eddyp , no reason - its never really come up. 

Are you able to work with just references to the items? If so you could use https://doc.rust-lang.org/beta/std/iter/trait.Extend.html or if you'd prefer to move them you could use https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append ?

A little example:
```rust
// Verify we can parse the example contained in the RSS 2.0 specification
#[test]
fn test_entries() {
    // Parse the feed
    let test_data = test::fixture_as_string("rss_2.0_spec_1.xml");
    let mut parsed1 = parser::parse(test_data.as_bytes()).unwrap();
    assert_eq!(2, parsed1.entries.len());
    let mut parsed2 = parser::parse(test_data.as_bytes()).unwrap();
    assert_eq!(2, parsed1.entries.len());

    let mut combined = Vec::new();
    combined.append(&mut parsed1.entries);
    combined.append(&mut parsed2.entries);
    assert_eq!(4, combined.len());
}
```

**Comment by eddyp** [comment]
> Are you able to work with just references to the items?

I'm working on this bad clone of the Yahoo! Pipes functionality which, among other things could have filters that transform the content of a feed (e.g. replace diacritics with the base character), so I would need new copies of the original Entry.

If you're curious, and want to look at some really awful code, you can check the code at https://github.com/c-rustacean/hyposoapie

Agreed, a more memory-friendly data structure like a COW would be a nice thing, especially since only some of the struct fiedls could be updated, but the lack of Clone is limiting at the moment.

> ```rust
> combined.append(&mut parsed1.entries);
>     combined.append(&mut parsed2.entries);
> ```

The reason is that multiple transformation/filtering chains could use the same feed as source, so one consuming - in your example - parsed2.entries would mean no other filter could use the same feed.

In my case I would rather have multiple immutable references to the entries, but that excludes the transformation type of filters.

I'll try for now to see if I can only use R/O, but I suspect not, since `append` consumes the other vector.
If I exclude transformations, I think I would need to use a `Vec<&Entry>` to make this work.

I might be mistaken, as this project is a vehicle for me learning Rust on some practical project.

TIA!

**Comment by eddyp** [comment]
I just had the time to check out third works from the git repo, and indeed, it appears l was able to implement a working "contains string" filter with this version:

https://github.com/c-rustacean/hyposoapie/blob/c41673c4d0f61a7d787540729e3aa05e63da1ea0/Cargo.lock#L88

**Comment by markpritchard** [comment]
Great news, thanks @eddyp . Next release will actually include media-rs support, so a little way off yet. But hopefully in the next few weeks.
