### ISSUE TITLE
license file no longer included with feed-rs crate

### ISSUE THREAD

**Issue by decathorpe** [feed-rs/feed-rs#75]
It looks like there was some internal refactoring - the Cargo.toml specifies to include "LICENSE", but the license file was apparently renamed to "LICENSE-MIT":

https://github.com/feed-rs/feed-rs/blob/master/feed-rs/Cargo.toml#L9

**Comment by markpritchard** [comment]
Thanks for picking this up @decathorpe - is there an automated tool that catches this problem?
(I'll run it as part of packaging the crate).

**Comment by decathorpe** [comment]
I don't know if there's a tool for this (though I am surprised that cargo didn't error out when the included file doesn't exist ...).

I noticed this because I updated the fedora RPM package for the feed-rs crate to the latest version and the build failed because the previously specified license file was gone.

**Comment by markpritchard** [comment]
Updated the path, will be included in the next release.
