### ISSUE TITLE
Error UnquotedValue parsing attributes

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#77]
An issue reported to me some time ago: https://gitlab.com/news-flash/news_flash_gtk/-/issues/154#note_446893398

This [`unwrap()`](https://github.com/feed-rs/feed-rs/blob/master/feed-rs/src/xml/mod.rs#L391) can cause an error. In the case above the error is `UnquotedValue(32)`.

My suggestion is to `filter_map` instead and ignore attributes that currently unwrap to an error. If that is an acceptable solution I can prepare a PR.

**Comment by markpritchard** [comment]
Hey @jangernert , yep - sounds like a great approach. Will look out for the PR :)

**Comment by jangernert** [comment]
@markpritchard Do you plan to commit any changes to `feed-rs` in the near future? As far as I can tell the crate is pretty stable and the only open issue is a rather big feature request. So would you mind putting out `0.4.1` only containing this fix?

**Comment by markpritchard** [comment]
I am planning on wrapping up the media support, and moving it to 0.9.

But no issues pushing out 0.4.1. Will push it out this weekend.
