### ISSUE TITLE
Json Feed support

### ISSUE THREAD

**Issue by jangernert** [feed-rs/feed-rs#8]
I know this one is a bit more exotic. But since the purpose of this crate is one size fits all for feeds it would be nice to have.

- [website](https://jsonfeed.org/)
- [specialized crate](https://crates.io/crates/jsonfeed)

Of course this should be prioritized pretty low, since it's rarely used in the wild.

**Comment by markpritchard** [comment]
That is a really interesting idea @jangernert I like it. Will spend some time adding it to feed-rs (but might just implement the parser directly rather than re-use the crate to reduce dependencies / mapping).

**Comment by markpritchard** [comment]
I added support for JSON Feed, feel free to raise any issues if you run into problems.
