### ISSUE TITLE
Upgrade minimum rustc version

### ISSUE THREAD

**Issue by markpritchard** [feed-rs/feed-rs#80]
We are currently tied to 1.39.0 due to it shipping in freedesktop 19.08.

Is this still a requirement @jangernert or can we bump to latest stable (1.48.0)?

**Comment by jangernert** [comment]
The latest stable SDK 20.08 is at 1.44.1

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/NEWS#L92
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/rust.bst#L114
